### ISSUE TITLE
TSFS source

### ISSUE THREAD

**Issue by MarkMa1990** [kostyfisik/fdtd-1d#1]
Hi Konstantin,

Have you introduced total-field scattered-field in 1d code?

Thanks,
Mark

**Comment by kostyfisik** [comment]
No. Did you mean TFSF?

**Comment by MarkMa1990** [comment]
Sorry, yeah. total field scattered field.

Konstantin Ladutenko ***@***.***> 于2021年3月26日周五 上午11:24写道：

**Comment by kostyfisik** [comment]
@MarkMa1990 I think you have solved this issue by your latest commit! Thank you!
